# Generated by Django 4.2.2 on 2023-06-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcar',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
