# Generated by Django 4.2.2 on 2023-06-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcars', '0002_alter_bookcar_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcar',
            name='your_offer',
            field=models.BigIntegerField(),
        ),
    ]
