# Generated by Django 4.2.2 on 2023-06-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcars', '0003_alter_bookcar_your_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcar',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
