# Generated by Django 4.2.2 on 2023-06-12 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellcars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellcar',
            name='phone',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator(message='Phone number must start with 9 and be 10 digits long.', regex='^9\\d{9}$'), django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='sellcar',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1995), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
