# Generated by Django 4.2.2 on 2023-06-12 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellcars', '0002_alter_sellcar_phone_alter_sellcar_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellcar',
            name='km_driven',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999)]),
        ),
    ]
