# Generated by Django 4.2.2 on 2023-06-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellcars', '0003_alter_sellcar_km_driven'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellcar',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
