# Generated by Django 4.2.2 on 2023-06-12 14:45

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellcars', '0004_alter_sellcar_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellcar',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='sellcar',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must start with 9 and be 10 digits long.', regex='^9\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='sellcar',
            name='user_id',
            field=models.BigIntegerField(blank=True),
        ),
    ]
