# Generated by Django 4.2.2 on 2023-06-16 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sellcars', '0005_alter_sellcar_created_date_alter_sellcar_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellcar',
            name='user_id',
        ),
        migrations.AddField(
            model_name='sellcar',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
