# Generated by Django 4.2.2 on 2023-06-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellcars', '0007_remove_sellcar_user_sellcar_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellcar',
            name='photos',
        ),
        migrations.AlterField(
            model_name='sellcar',
            name='user_id',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
