# Generated by Django 4.2.2 on 2023-06-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellcars', '0009_photo_sellcar_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellcar',
            name='user_id',
            field=models.BigIntegerField(blank=True),
        ),
    ]
