# Generated by Django 4.2.2 on 2023-06-30 03:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellcars', '0010_alter_sellcar_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='media/car_photos'),
        ),
        migrations.AlterField(
            model_name='sellcar',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1994), django.core.validators.MaxValueValidator(2024)]),
        ),
    ]
