# Generated by Django 4.2.2 on 2023-06-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlist', '0002_alter_car_kms_driven_alter_car_name_alter_car_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/carz/%Y/%m/'),
        ),
    ]
