# Generated by Django 4.2.2 on 2023-06-06 10:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlist', '0003_car_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='categories',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Hatchback', 'Hatchback'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible'), ('Mini van', 'Mini van'), ('Pickup', 'Pickup'), ('Sports Car', 'Sports Car'), ('Luxury Car', 'Luxury Car')], max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('LPG', 'LPG')], max_length=255),
        ),
    ]
